### ISSUE TITLE
Feature Request: webp image format support

### ISSUE THREAD

**Issue by dominic-p** [TimothyYe/bing-wallpaper#22]
First, thanks for the very useful service. I really appreciate it.

I noticed that Bing seems to support delivering WebP images instead of JPEG if you just change the file extension in the URL to the image. However, when using `format=image` in CSS I can't think of a way to access the WebP version of the image. Maybe a new query string parameter like `image_format` could be added with values like (`jpg` and `webp`) so we could request the WebP version directly to save a few bytes?

Unfortunately, go isn't a language I know, or else I would send a PR.

**Comment by TimothyYe** [comment]
Hi @dominic-p , I'm not sure whether Bing supports WebP images, do you have an example URL or the related document?

**Comment by dominic-p** [comment]
I was just playing around the with the URL to see what I could get. For example, today's image URL from the [JSON document](https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=zh-CN) is:

https://bing.com/th?id=OHR.BanyakIslands_ZH-CN6620304821_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp

If you just change the file extensions from .jpg to .webp you get the same image in WebP format:

https://bing.com/th?id=OHR.BanyakIslands_ZH-CN6620304821_1920x1080.webp&rf=LaDigue_1920x1080.webp&pid=hp

It's definitely a hack, but it seems to work.

__Update:__ The WebP version doesn't seem to be available for today's image if we specify the [UHD resolution](https://bing.com/th?id=OHR.BanyakIslands_ZH-CN6620304821_UHD.webp&rf=LaDigue_UHD.webp&pid=hp). So, this could be problematic.

**Comment by TimothyYe** [comment]
I see, thanks for the explanation. Let me implement it.

**Comment by TimothyYe** [comment]
@dominic-p It's done, you could try with this request:
https://bing.biturl.top/?format=image&image_format=webp

**Comment by dominic-p** [comment]
Dude! You're amazing. Thanks for making that happen so quickly. It works beautifully. Now we just need Bing to start providing a WebP for the 4k resolution. :)

**Comment by TimothyYe** [comment]
Looking forward to it.
