### ISSUE TITLE
Wallpaper orientation

### ISSUE THREAD

**Issue by abhi12choudhary** [TimothyYe/bing-wallpaper#28]
Is there a way to change format of the image. I mean, to have it in vericatal format rather than landscape. Similar to what we get from the bing android app/launcher.

**Comment by TimothyYe** [comment]
Yes, it's possible.

**Comment by TimothyYe** [comment]
Now you can try with different resolutions

https://bing.biturl.top/?resolution=768x1280&format=json&index=0&mkt=zh-CN

For more resolutions, pls refer to the README.
