### ISSUE TITLE
URL blocked by antivirus

### ISSUE THREAD

**Issue by onyxiarivera** [TimothyYe/bing-wallpaper#3]
It appears that AVG Antivirus has blacklisted your URL, bing.biturl.top. I'm not sure how to fix this, just thought I'd let you know.

**Comment by TimothyYe** [comment]
I think my answer is the same as yours, I've no idea about what to do with this...

**Comment by onyxiarivera** [comment]
> I think my answer is the same as yours, I've no idea about what to do with this...

Such a shame :( I'll let you know if anything changes
