### ISSUE TITLE
bing.biturl.top: HTTP 500 when any parameter is used

### ISSUE THREAD

**Issue by jaller94** [TimothyYe/bing-wallpaper#30]
Hi Timothy,
thank you so much for this great wallpaper downloader and for hosting it as a simple-to-use service~

If you have time, there seem to be server issues, that you might be able to fix.

For the past three days, when any parameter is used, the server at bing.biturl.top responds with HTTP 500.

* https://bing.biturl.top/?format=image
* https://bing.biturl.top/?mkt=zh-CN
* https://bing.biturl.top/?resolution=1920x1200

The only URL that seems to work and still has up-to-date images is https://bing.biturl.top/

**Comment by pitsi** [comment]
I also have this issue, so thank you for opening the report before me. However, I noticed it ~1 hour ago and I had no issues the days before today. I have a small page which uses this as its background
`https://bing.biturl.top/?resolution=1280x768&format=image&mkt=ja-JP`
and it did not refresh at the expected time (7pm EEST where I am is midnight in Japan), so I investigated it a bit.

On my end, the only market that works now is zh-CN. As for the resolutions, only 1920 ~and 1366~ seem to work. One hour ago the market for en-US used also to work, and the uhd resolution too. Now they do not. Proof
```
$ curl -s https://bing.biturl.top/?mkt=zh-CN
{"start_date":"20241009","end_date":"20241010","url":"https://www.bing.com/th?id=OHR.SoranoItaly_ZH-CN5842160079_1920x1080.jpg","copyright":"索拉诺，托斯卡纳，意大利 (© Luigi Vaccarella/eStock Photo)","copyright_link":"https://www.bing.com/search?q=%E6%84%8F%E5%A4%A7%E5%88%A9%E7%B4%A2%E6%8B%89%E8%AF%BA%E5%B8%82\u0026form=hpcapt\u0026mkt=zh-cn"}

$ curl -s https://bing.biturl.top/?resolution=1920
{"start_date":"20241009","end_date":"20241010","url":"https://www.bing.com/th?id=OHR.SoranoItaly_ZH-CN5842160079_1920x1080.jpg","copyright":"索拉诺，托斯卡纳，意大利 (© Luigi Vaccarella/eStock Photo)","copyright_link":"https://www.bing.com/search?q=%E6%84%8F%E5%A4%A7%E5%88%A9%E7%B4%A2%E6%8B%89%E8%AF%BA%E5%B8%82\u0026form=hpcapt\u0026mkt=zh-cn"}
```
Aaand 1366 stopped working as I was writing those lines :D

**Comment by pitsi** [comment]
The api seems to be working fine now, at least on my end and regardless of market or resolution.
Can someone verify it works for them too and close the issue?

```
$ curl -s https://bing.biturl.top/?mkt=random
{"start_date":"20241008","end_date":"20241009","url":"https://www.bing.com/th?id=OHR.AspensColorado_EN-CA0556453730_1920x1080.jpg","copyright":"Aspens near Marble, Colorado, USA (© Jason Hatfield/TANDEM Stills + Motion)","copyright_link":"https://www.bing.com/search?q=Aspen+tree\u0026form=hpcapt\u0026filters=HpDate%3a%2220241009_0400%22"}

$ curl -s https://bing.biturl.top/?mkt=random
{"start_date":"20241009","end_date":"20241010","url":"https://www.bing.com/th?id=OHR.SoranoItaly_JA-JP6459075522_1920x1080.jpg","copyright":"ソラーノ, イタリア トスカーナ州 (© Luigi Vaccarella/eStock Photo)","copyright_link":"https://www.bing.com/search?q=%E3%82%BD%E3%83%A9%E3%83%BC%E3%83%8E+%E3%82%A4%E3%82%BF%E3%83%AA%E3%82%A2\u0026form=hpcapt\u0026filters=HpDate%3a%2220241009_1500%22"}
```

**Comment by jaller94** [comment]
Yes, it recovered.

**Comment by TimothyYe** [comment]
Hi @pitsi @jaller94 , just see this issue, but it is closed already.
Any ideas for reproducing this issue?

**Comment by pitsi** [comment]
It was probably something server sided, so let's not reproduce it :)
I wish I had the knowledge to selfhost the api and provide more info.

**Comment by pitsi** [comment]
Sorry for bringing this back to the surface, but the site returns a 500 error for the last a few hours (I last checked 5 hours ago and just now)
```
This page isn’t working
bing.biturl.top is currently unable to handle this request.
HTTP ERROR 500
```
and the api returns nothing at all
```
$ curl https://bing.biturl.top/?mkt=random 
$
```

**Comment by chriscomeau** [comment]
Same for me https://github.com/TimothyYe/bing-wallpaper/issues/39

**Comment by chriscomeau** [comment]
...looks like its now fixed 🎉

**Comment by pitsi** [comment]
Yeap, it is fixed now!
```
$ curl https://bing.biturl.top/?mkt=random
{"start_date":"20251014","end_date":"20251015","url":"https://www.bing.com/th?id=OHR.AmethystLaccaria_FR-FR2437866835_1920x1080.jpg","copyright":"Champignon laccaria amethystina, Seabeck, Washington, États-Unis (© Danita Delimont/Shutterstock)","copyright_link":"https://www.bing.com/search?q=Laccaria+amethystina\u0026form=hpcapt\u0026filters=HpDate%3a%2220251014_2200%22"
```

**Comment by TimothyYe** [comment]
> Sorry for bringing this back to the surface, but the site returns a 500 error for the last a few hours (I last checked 5 hours ago and just now)
> 
> ```
> This page isn’t working
> bing.biturl.top is currently unable to handle this request.
> HTTP ERROR 500
> ```
> 
> and the api returns nothing at all
> 
> ```
> $ curl https://bing.biturl.top/?mkt=random 
> $
> ```

This issue is caused by the `user-agent` of the HTTP request. I've fixed it.
