### ISSUE TITLE
[Enhancement] Image Title Field

### ISSUE THREAD

**Issue by omerasif57** [TimothyYe/bing-wallpaper#5]
That would be great if you could add `title` field as well. (As per your convenience)
I could have made a pull request but I don't have an env for go and There are only couple of lines needed, I guess. :)

**Comment by TimothyYe** [comment]
Let me check it

**Comment by TimothyYe** [comment]
Actually, I think you can treat the `copyright` field as `title`?

**Comment by omerasif57** [comment]
If we see `JSON` format it has a `title` field unlike `RSS` or `XML` format.
JSON: https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US

Anyway. Parsing `Copyright` will work for now. Thanks :)
