### ISSUE TITLE
What does index parameter do?

### ISSUE THREAD

**Issue by maartenvandillen** [TimothyYe/bing-wallpaper#9]
Hi, thanks for your web service. What exactly does the index parameter do? If I change it I sometimes get another image, sometimes the same. What is the range of the parameter? Do I need to change it daily? Or is the image changing every day without the index parameter?

Thanks

**Comment by TimothyYe** [comment]
@maartenvandillen `index` is just one offset of the date.
By default,  `index=0` means to get today's image, `index=1` means to get yesterday's image, and so on...

I don't think you need to change it, to use the `index=0` means always use today's image, and `Bing` always changes the image daily.

**Comment by maartenvandillen** [comment]
Thanks, all clear now. Android image cache was messing up things. I have added a unique parameter to the url to fix this.

**Comment by TimothyYe** [comment]
Good to hear that! Then I'll close this issue.
